CREATE TABLE TB_SETTLE_MASTER (
    SETTLE_NO VARCHAR2(20) NOT NULL,
    MTC_AT NUMBER(2),
    AMOUNT NUMBER(15, 2),
    REG_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_SETTLE_MASTER PRIMARY KEY (SETTLE_NO)
);

COMMENT ON COLUMN TB_SETTLE_MASTER.SETTLE_NO IS '정산 일련번호 (PK)';
COMMENT ON COLUMN TB_SETTLE_MASTER.MTC_AT IS '점검 상태 코드';
COMMENT ON COLUMN TB_SETTLE_MASTER.AMOUNT IS '정산 금액';
